// app/layout.js
import './styles/globals.css';
import SideMenu from "./components/SideMenu/SideMenu";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SideMenu />  {/* Innerhalb vom body! */}
        {children}
      </body>
    </html>
  );
}